version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=quiz_pengupil

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE=quiz_pengupil
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./quiz_pengupil.sql:/docker-entrypoint-initdb.d/quiz_pengupil.sql

volumes:
  mysql_data:
