name: CI Pipeline with Docker

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:  # Indentasi harus sejajar dengan runs-on
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: quiz_pengupil
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build PHP Docker Image
        run: docker build -t quiz-php-app .

      - name: Create Docker Network
        run: docker network create quiz_network

      - name: Import MySQL Database  # Perbaiki indentasi
        run: |
          sleep 30 # Tunggu MySQL siap
          docker cp quiz_pengupil.sql $(docker ps -q -f name=mysql):/quiz_pengupil.sql
          docker exec $(docker ps -q -f name=mysql) sh -c 'mysql -u root -proot quiz_pengupil < /quiz_pengupil.sql'

      - name: Run PHP Application
        run: |
          docker run -d --name php-app \
            --network=quiz_network \
            -p 8000:80 \
            quiz-php-app

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python Dependencies
        run: pip install selenium

      - name: Run Selenium Tests
        run: python -m unittest testing.py

