name: CI Test

on: [push, pull_request]  # Run on every push and pull request

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Start PHP Server
        run: php -S localhost:8000 -t . &
      
      - name: Import MySQL Database
        run: |
          sudo apt-get install -y mysql-client
          mysql -h 127.0.0.1 -u root -proot testdb < database.sql

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python Dependencies
        run: pip install selenium unittest

      - name: Run Selenium Tests
        run: python -m unittest testing.py
